force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Forks_Count__c.field-meta.xml
<CustomField>
    <fullName>Forks_Count__c</fullName>
    <label>Forks Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/GitHub_Id__c.field-meta.xml
<CustomField>
    <fullName>GitHub_Id__c</fullName>
    <externalId>true</externalId>
    <label>GitHub Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Owner_Login__c.field-meta.xml
<CustomField>
    <fullName>Owner_Login__c</fullName>
    <label>Owner Login</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Stargazers_Count__c.field-meta.xml
<CustomField>
    <fullName>Stargazers_Count__c</fullName>
    <label>Stargazers Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RepositoryControllerTest.cls
/**
 * @description       : Classe de teste para RepositoryController
 * @author            : Jefferson Martins
 * @group             : 
 * @last modified on  : 12-28-2021
 * @last modified by  : Jefferson Martins
**/
@IsTest
public class RepositoryControllerTest {

    @IsTest
    public static void getRepositoriesTest() {
        addRepositories(10);

        Test.startTest();
        List<Repository__c> repositoriesList = RepositoryController.getRepositories();
        Test.stopTest();

        System.assertEquals(10, repositoriesList.size(), 'Expected 10, but found ' + repositoriesList.size());
    }

    @IsTest
    public static void getRepositoriesErrorTest() {
        RepositoryController.forceException = true;
        Test.startTest();
        try {
            List<Repository__c> repositoriesList = RepositoryController.getRepositories();
        } catch (HandledException e) {
            String message = e.getMessage();
            System.assertEquals('Force exception by class test', message, 'Was expected Exception message: "Force exception by class test", but found: "' + message + '"');  
        }

        Test.stopTest();

    }

    private static void addRepositories(Integer numberOfRepositories) {
        List<Repository__c> repositoriesList = new List<Repository__c>();
        for (Integer i = 0; i < numberOfRepositories; i++) {
            Repository__c repository = new Repository__c();
            repository.Name = 'Repo' + i;
            repository.Forks_Count__c = i;
            repository.GitHub_Id__c = i;
            repository.Language__c = 'Java';
            repository.Owner_Login__c = 'owner' + i;
            repository.Stargazers_Count__c = i;
            repository.Url__c = 'https://test.com';

            repositoriesList.add(repository);
        }

        insert repositoriesList;
    }
}