force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Forks_Count__c.field-meta.xml
<CustomField>
    <fullName>Forks_Count__c</fullName>
    <label>Forks Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/GitHub_Id__c.field-meta.xml
<CustomField>
    <fullName>GitHub_Id__c</fullName>
    <externalId>true</externalId>
    <label>GitHub Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Owner_Login__c.field-meta.xml
<CustomField>
    <fullName>Owner_Login__c</fullName>
    <label>Owner Login</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Stargazers_Count__c.field-meta.xml
<CustomField>
    <fullName>Stargazers_Count__c</fullName>
    <label>Stargazers Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RepositoryController.cls
/**
 * @description       : Classe controller para o Repository__c
 * @author            : Jefferson Martins
 * @group             : 
 * @last modified on  : 12-28-2021
 * @last modified by  : Jefferson Martins
**/
public class RepositoryController {


    @testVisible private static Boolean forceException = false;

    @AuraEnabled(cacheable=true)
    public static List<Repository__c> getRepositories(){
        try {

            if (forceException){
                throw new HandledException('Force exception by class test');
            }

            return [SELECT Id, Name, 
                        Stargazers_Count__c, 
                        Forks_Count__c,
                        GitHub_Id__c,
                        Language__c,
                        Url__c,
                        Owner_Login__c
                    FROM Repository__c
                    ORDER BY Stargazers_Count__c DESC];

        } catch (Exception e) {            
            throw new HandledException(e.getMessage());
        }
    }


}