force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Forks_Count__c.field-meta.xml
<CustomField>
    <fullName>Forks_Count__c</fullName>
    <label>Forks Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/GitHub_Id__c.field-meta.xml
<CustomField>
    <fullName>GitHub_Id__c</fullName>
    <externalId>true</externalId>
    <label>GitHub Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Owner_Login__c.field-meta.xml
<CustomField>
    <fullName>Owner_Login__c</fullName>
    <label>Owner Login</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Stargazers_Count__c.field-meta.xml
<CustomField>
    <fullName>Stargazers_Count__c</fullName>
    <label>Stargazers Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RepositoryService_Callout.cls
/**
 * @description       : Classe responsável por realizar a sincronização dos repositórios do github com mais estrelas.
 * @author            : Jefferson Martins
 * @group             : 
 * @last modified on  : 12-28-2021
 * @last modified by  : Jefferson Martins
**/
public class RepositoryService_Callout {
    private final static String URL_REPOSITORIES = 'https://api.github.com/search/repositories?q=language:Java&sort=stars&per_page=100&page={0}';
    private final static String METHOD_GET = 'GET';

    @future(callout=true)
    public static void getRepositories() {
        List<Repository__c> repositoriesList = new List<Repository__c>();
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        Boolean hasMorePage = true;
        Integer pageNumber = 1;
        while (hasMorePage) {

            request.setEndpoint(String.format(URL_REPOSITORIES, new List<String>{String.valueOf(pageNumber)}));
            request.setMethod(METHOD_GET);

            HttpResponse response = http.send(request);
            hasMorePage = response.getStatusCode() == 200;
            
            if (!hasMorePage) {
                break;
            }

            Map<String, Object> repositories = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            List<Object> repositoriesItems = (List<Object>)repositories.get('items');            
    
            for (Integer i = 0; i < repositoriesItems.size(); i++) {
                Map<String, Object> repository = (Map<String, Object>)repositoriesItems[i];
                Map<String, Object> owner = (Map<String, Object>)repository.get('owner');
                Repository__c repositoryObj = new Repository__c(Name = (String)repository.get('name'),
                                                                Stargazers_Count__c = (Integer)repository.get('stargazers_count'),
                                                                Forks_Count__c =  (Integer)repository.get('forks_count'),
                                                                GitHub_Id__c = (Integer)repository.get('id'),
                                                                Language__c = (String)repository.get('language'),
                                                                Url__c = (String)repository.get('html_url'),
                                                                Owner_Login__c = (String)owner.get('login')
                                                                );
                
                repositoriesList.add(repositoryObj);            
            }  

            pageNumber++;
        }

        if (repositoriesList.size() > 0) {
            delete [SELECT Id FROM Repository__c];
        
            insert repositoriesList;
        }
    }

}